/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lp2;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author pere
 */
public class UtilidadesProfesor extends javax.swing.JDialog {

    /**
     * Creates new form UtilidadesAula
     */
    Asignatura asig = new Asignatura();
    DefaultListModel modeloListaAsigAlta = new DefaultListModel();
    DefaultListModel modeloListaAsigDeProf = new DefaultListModel();
    DefaultListModel modeloListaAsigDeProfMod = new DefaultListModel();
    DefaultListModel modeloListaAsigMod = new DefaultListModel();
    Profesor profesor = new Profesor();

    public UtilidadesProfesor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        rellenarJlistAlta();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTFNombreAlta = new javax.swing.JTextField();
        jTFTelefonoAlta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLAsignarurasDeProfesorAlta = new javax.swing.JList();
        botonAddAsignaturaAlta = new javax.swing.JButton();
        botonOKAlta = new javax.swing.JButton();
        botonLimpiarAlta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonEliminarAsignaturaAlta = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jLAsignaturasAlta = new javax.swing.JList();
        jFTFNifAlta = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTAConsulta = new javax.swing.JTextArea();
        botonBuscarConsulta = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jFTFNifConsulta = new javax.swing.JFormattedTextField();
        jPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTFNombreModificacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFTelefonoModificacion = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLAsignarurasDeProfesorModificacion = new javax.swing.JList();
        botonAddAsignaturaModificacio = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        botonEliminarAsignaturaProfModificacio = new javax.swing.JButton();
        botonOKModificacio = new javax.swing.JButton();
        botonLimpiarmod = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jLAsignarurasModificacion = new javax.swing.JList();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        botonBuscarNifModificacion = new javax.swing.JButton();
        jFTFNifBuscarModificacion = new javax.swing.JFormattedTextField();
        jFTFNifModificacion = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        botonLimpiarBajaEstudio = new javax.swing.JButton();
        botonEliminarBajaEstudio = new javax.swing.JButton();
        jFTFNifBaja = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(jLAsignarurasDeProfesorAlta);

        botonAddAsignaturaAlta.setText(">>");
        botonAddAsignaturaAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAddAsignaturaAltaActionPerformed(evt);
            }
        });

        botonOKAlta.setText("OK");
        botonOKAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOKAltaActionPerformed(evt);
            }
        });

        botonLimpiarAlta.setText("Limpiar");
        botonLimpiarAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarAltaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("Nif:");

        jLabel3.setText("Telefono:");

        jLabel4.setText("Asignaturas:");

        botonEliminarAsignaturaAlta.setText("<<");
        botonEliminarAsignaturaAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarAsignaturaAltaActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(jLAsignaturasAlta);

        jFTFNifAlta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFTFNifAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFNifAltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(23, 23, 23))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFTelefonoAlta)
                    .addComponent(jTFNombreAlta)
                    .addComponent(jFTFNifAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(botonLimpiarAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(botonOKAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(135, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonAddAsignaturaAlta)
                                    .addComponent(botonEliminarAsignaturaAlta))
                                .addGap(23, 23, 23)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFNombreAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jFTFNifAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFTelefonoAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(botonAddAsignaturaAlta)
                        .addGap(18, 18, 18)
                        .addComponent(botonEliminarAsignaturaAlta))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonOKAlta)
                    .addComponent(botonLimpiarAlta))
                .addGap(47, 47, 47))
        );

        jTabbedPane1.addTab("Alta", jPanel1);

        jTAConsulta.setColumns(20);
        jTAConsulta.setRows(5);
        jScrollPane3.setViewportView(jTAConsulta);

        botonBuscarConsulta.setText("Buscar");
        botonBuscarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarConsultaActionPerformed(evt);
            }
        });

        jLabel10.setText("NIf:");

        jFTFNifConsulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jFTFNifConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonBuscarConsulta))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscarConsulta)
                    .addComponent(jLabel10)
                    .addComponent(jFTFNifConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consulta", jPanel4);

        jLabel5.setText("Nombre:");

        jLabel6.setText("Nif:");

        jLabel7.setText("Telefono:");

        jScrollPane2.setViewportView(jLAsignarurasDeProfesorModificacion);

        botonAddAsignaturaModificacio.setText(">>");
        botonAddAsignaturaModificacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAddAsignaturaModificacioActionPerformed(evt);
            }
        });

        jLabel8.setText("Asignaturas:");

        botonEliminarAsignaturaProfModificacio.setText("<<");
        botonEliminarAsignaturaProfModificacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarAsignaturaProfModificacioActionPerformed(evt);
            }
        });

        botonOKModificacio.setText("OK");
        botonOKModificacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOKModificacioActionPerformed(evt);
            }
        });

        botonLimpiarmod.setText("Limpiar");
        botonLimpiarmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarmodActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(jLAsignarurasModificacion);

        jLabel11.setText("Nif:");

        botonBuscarNifModificacion.setText("Buscar");
        botonBuscarNifModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarNifModificacionActionPerformed(evt);
            }
        });

        jFTFNifBuscarModificacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jFTFNifModificacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(23, 23, 23))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFTFNifModificacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTFTelefonoModificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                .addComponent(jTFNombreModificacion)))
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addComponent(botonLimpiarmod, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60)
                                        .addComponent(botonOKModificacio, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonAddAsignaturaModificacio, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(botonEliminarAsignaturaProfModificacio, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(25, 25, 25))))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jFTFNifBuscarModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonBuscarNifModificacion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(botonBuscarNifModificacion)
                    .addComponent(jFTFNifBuscarModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelLayout.createSequentialGroup()
                                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTFNombreModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelLayout.createSequentialGroup()
                                            .addGap(35, 35, 35)
                                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel6)
                                                .addComponent(jFTFNifModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(34, 34, 34)
                                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTFTelefonoModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel7)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(botonAddAsignaturaModificacio)
                                            .addGap(18, 18, 18)
                                            .addComponent(botonEliminarAsignaturaProfModificacio)
                                            .addGap(70, 70, 70))))
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonOKModificacio)
                            .addComponent(botonLimpiarmod))
                        .addGap(21, 21, 21))))
        );

        jTabbedPane1.addTab("Modificacion", jPanel);

        jLabel9.setText("Nif:");

        botonLimpiarBajaEstudio.setText("Limpiar");
        botonLimpiarBajaEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarBajaEstudioActionPerformed(evt);
            }
        });

        botonEliminarBajaEstudio.setText("Eliminar");
        botonEliminarBajaEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarBajaEstudioActionPerformed(evt);
            }
        });

        jFTFNifBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFNifBajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel9)
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(botonLimpiarBajaEstudio)
                        .addGap(38, 38, 38)
                        .addComponent(botonEliminarBajaEstudio))
                    .addComponent(jFTFNifBaja))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jFTFNifBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEliminarBajaEstudio)
                    .addComponent(botonLimpiarBajaEstudio))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Baja", jPanel3);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Visualización", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonOKAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOKAltaActionPerformed
        if ("".equals(jTFNombreAlta.getText()) || "".equals(jFTFNifAlta.getText().toString()) || "".equals(jTFTelefonoAlta.getText().toString())) {

            JOptionPane.showMessageDialog(null,
                    "Hay campos vacios",
                    "Aletra",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            boolean existeix = false;
            Iterator<Profesor> itArrayProf = inici.ArrayLProfesor.iterator();
            Object[] nomAsignatures = modeloListaAsigDeProf.toArray();
            Asignatura[] asignaturas = new Asignatura[nomAsignatures.length];
            while (itArrayProf.hasNext()) {
                profesor = (Profesor) itArrayProf.next();
                if (String.valueOf(profesor.getNif()).equals(jFTFNifAlta.getText())) {
                    existeix = true;
                    JOptionPane.showMessageDialog(null,
                            "Ya se ha dado de alta este profesor",
                            "Aletra",
                            JOptionPane.WARNING_MESSAGE);
                }
            }
            if (!existeix) {
                for (int i = 0; i < nomAsignatures.length; i++) {
                    Iterator itArrayAsig = inici.ArrayLAsignaturas.iterator();
                    while (itArrayAsig.hasNext()) {
                        asig = (Asignatura) itArrayAsig.next();
                        if (asig.getNombre().equals(nomAsignatures[i])) {
                            asignaturas[i] = asig;
                            System.out.println(asig.toString());
                        }
                        System.out.println(i);
                    }
                }

                Profesor profesor = new Profesor(jTFNombreAlta.getText(), Integer.parseInt(jFTFNifAlta.getText()), jTFTelefonoAlta.getText(), asignaturas);
                inici.ArrayLProfesor.add(profesor);
                System.out.println(profesor.toString());

            }
        }
    }//GEN-LAST:event_botonOKAltaActionPerformed

    private void botonAddAsignaturaAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAddAsignaturaAltaActionPerformed
        if (jLAsignaturasAlta.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(null,
                    "Selecciona asignatura",
                    "Informacion",
                    JOptionPane.WARNING_MESSAGE);
            jFTFNifBaja.setText("");

        } else {
            modeloListaAsigDeProf.addElement(jLAsignaturasAlta.getSelectedValue());
            modeloListaAsigAlta.removeElementAt(jLAsignaturasAlta.getSelectedIndex());
            jLAsignarurasDeProfesorAlta.setModel(modeloListaAsigDeProf);

        }
    }//GEN-LAST:event_botonAddAsignaturaAltaActionPerformed

    private void jFTFNifAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTFNifAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTFNifAltaActionPerformed

    private void botonLimpiarAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarAltaActionPerformed

        jTFNombreAlta.setText("");
        jFTFNifAlta.setText("");
        jTFTelefonoAlta.setText("");
        rellenarJlistAlta();
        borrarModeloAsigProf();
        jLAsignarurasDeProfesorAlta.setModel(modeloListaAsigDeProf);
    }//GEN-LAST:event_botonLimpiarAltaActionPerformed

    private void botonBuscarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarConsultaActionPerformed
        Iterator itArrayProfessor = inici.ArrayLProfesor.iterator();
        boolean trobat = false;
        if ("".equals(jFTFNifConsulta.getText())) {

            JOptionPane.showMessageDialog(null,
                    "No has escrito ningun identificador",
                    "Aletra",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            if (!inici.ArrayLProfesor.isEmpty()) {

                while (itArrayProfessor.hasNext()) {
                    profesor = (Profesor) itArrayProfessor.next();
                    System.out.println(profesor.getNif() + " == " + Integer.parseInt(jFTFNifConsulta.getText()));
                    if (profesor.getNif() == Integer.parseInt(jFTFNifConsulta.getText())) {
                        trobat = true;
                        jTAConsulta.setText(profesor.toString());
                       
                    }
                }
                if (!trobat) {
                    jTAConsulta.setText("No hay ningun profesor dado de alta con este Nif");
                }

            } else {
                jTAConsulta.setText("No hay ningun profesor dado de alta");

            }
        }
    }//GEN-LAST:event_botonBuscarConsultaActionPerformed

    private void botonOKModificacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOKModificacioActionPerformed
        boolean existeix = false;
        if ("".equals(jTFNombreModificacion.getText()) || "".equals(jFTFNifModificacion.getText()) || "".equals(jTFTelefonoModificacion.getText())) {

            JOptionPane.showMessageDialog(null,
                    "Hay campos vacios",
                    "Aletra",
                    JOptionPane.WARNING_MESSAGE);
        } else {

            Iterator<Profesor> itArrayProf = inici.ArrayLProfesor.iterator();
            Object[] nomAsignatures = modeloListaAsigDeProfMod.toArray();
            Asignatura[] asignaturas = new Asignatura[nomAsignatures.length];

            while (itArrayProf.hasNext() && !existeix) {
                profesor = (Profesor) itArrayProf.next();
                if (String.valueOf(profesor.getNif()).equals(jFTFNifBuscarModificacion.getText())) {
                    existeix = true;
                    //omplim array de asignatures del professor
                    for (int i = 0; i < nomAsignatures.length; i++) {

                        Iterator itArrayAsig = inici.ArrayLAsignaturas.iterator();

                        while (itArrayAsig.hasNext()) {
                            asig = (Asignatura) itArrayAsig.next();
                            if (asig.getNombre().equals(nomAsignatures[i])) {
                                asignaturas[i] = asig;
                                System.out.println(asig.toString());
                            }
                            System.out.println(i);
                        }
                    }
                    profesor.setNombre(jTFNombreModificacion.getText());
                    profesor.setNif(Integer.parseInt(jFTFNifModificacion.getText()));
                    profesor.setAsignaturas(asignaturas);
                    profesor.setTelofono(jTFTelefonoModificacion.getText());
                    System.out.println("");
                    System.out.println(profesor.toString());
                    System.out.println("success");
                }
            }
        }
    }//GEN-LAST:event_botonOKModificacioActionPerformed

    private void botonBuscarNifModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarNifModificacionActionPerformed
        Iterator itArrayProfessor = inici.ArrayLProfesor.iterator();
        System.out.println("Hola hem fet s'iterador");
        limiarCamposBuscar();
        if ("".equals(jFTFNifBuscarModificacion.getText())) {

            JOptionPane.showMessageDialog(null,
                    "No has escrito ningun identificador",
                    "Aletra",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            if (!inici.ArrayLProfesor.isEmpty()) {//miram si s'array de professors esta ple

                while (itArrayProfessor.hasNext()) {// metres tengui prof. itera
                    profesor = (Profesor) itArrayProfessor.next();

                    if (profesor.getNif() == Integer.parseInt(jFTFNifBuscarModificacion.getText())) {
                        //quan troba el professor asigna valors als components del panell
                        jTFNombreModificacion.setText(profesor.getNombre());
                        jTFTelefonoModificacion.setText(profesor.getTelofono());
                        jFTFNifModificacion.setText(String.valueOf(profesor.getNif()));
                        //posam ses asignatures a nes Jlist
                        rellenarJlistProfMod(profesor.getAsignaturas());
                        rellenarJlistMod(profesor.getAsignaturas());
                    }
                }
                System.out.println("fora bucle");
            } else {
                jTAConsulta.setText("No hay ningun profesor dado de alta");

            }
        }
    }//GEN-LAST:event_botonBuscarNifModificacionActionPerformed

    private void botonEliminarAsignaturaAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarAsignaturaAltaActionPerformed
        if (jLAsignarurasDeProfesorAlta.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(null,
                    "Selecciona asignatura",
                    "Informacion",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            modeloListaAsigAlta.addElement(jLAsignarurasDeProfesorAlta.getSelectedValue());
            modeloListaAsigDeProf.removeElementAt(jLAsignarurasDeProfesorAlta.getSelectedIndex());
            jLAsignaturasAlta.setModel(modeloListaAsigAlta);
            
        }
    }//GEN-LAST:event_botonEliminarAsignaturaAltaActionPerformed

    private void botonLimpiarmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarmodActionPerformed
        modeloListaAsigDeProfMod = new DefaultListModel();
        modeloListaAsigMod = new DefaultListModel();
        jLAsignarurasDeProfesorModificacion.setModel(modeloListaAsigDeProfMod);
        jLAsignarurasModificacion.setModel(modeloListaAsigMod);
        jTFNombreModificacion.setText("");
        jTFTelefonoModificacion.setText("");
        jFTFNifModificacion.setText("");
        jFTFNifBuscarModificacion.setText("");
    }//GEN-LAST:event_botonLimpiarmodActionPerformed

    private void botonEliminarBajaEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarBajaEstudioActionPerformed
        Iterator itArrayProfesores = inici.ArrayLProfesor.iterator();

        if (!inici.ArrayLAsignaturas.isEmpty()) {

            while (itArrayProfesores.hasNext()) {
                profesor = (Profesor) itArrayProfesores.next();
                if (profesor.getNif() == Integer.parseInt(jFTFNifBaja.getText())) {
                    itArrayProfesores.remove();
                    JOptionPane.showMessageDialog(null,
                            "Se ha eliminado correctamente",
                            "Informacion",
                            JOptionPane.INFORMATION_MESSAGE);
                    jFTFNifBaja.setText("");

                }
            }
        }
    }//GEN-LAST:event_botonEliminarBajaEstudioActionPerformed

    private void jFTFNifBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTFNifBajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTFNifBajaActionPerformed

    private void botonLimpiarBajaEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarBajaEstudioActionPerformed
        jFTFNifBaja.setText("");
    }//GEN-LAST:event_botonLimpiarBajaEstudioActionPerformed

    private void botonAddAsignaturaModificacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAddAsignaturaModificacioActionPerformed

        if (jLAsignarurasModificacion.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(null,
                    "Selecciona asignatura",
                    "Informacion",
                    JOptionPane.WARNING_MESSAGE);
            jFTFNifBaja.setText("");

        } else {
            modeloListaAsigDeProfMod.addElement(jLAsignarurasModificacion.getSelectedValue());
            modeloListaAsigMod.removeElementAt(jLAsignarurasModificacion.getSelectedIndex());
            jLAsignarurasDeProfesorModificacion.setModel(modeloListaAsigDeProfMod);
        }

    }//GEN-LAST:event_botonAddAsignaturaModificacioActionPerformed

    private void botonEliminarAsignaturaProfModificacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarAsignaturaProfModificacioActionPerformed

        if (jLAsignarurasDeProfesorModificacion.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(null,
                    "Selecciona asignatura",
                    "Informacion",
                    JOptionPane.WARNING_MESSAGE);
            jFTFNifBaja.setText("");

        } else {
            modeloListaAsigMod.addElement(jLAsignarurasDeProfesorModificacion.getSelectedValue());
            modeloListaAsigDeProfMod.removeElementAt(jLAsignarurasDeProfesorModificacion.getSelectedIndex());
            jLAsignarurasDeProfesorModificacion.setModel(modeloListaAsigDeProfMod);
        }
    }//GEN-LAST:event_botonEliminarAsignaturaProfModificacioActionPerformed

    private void rellenarJlistAlta() {
        Iterator itArrayAsig = inici.ArrayLAsignaturas.iterator();
        modeloListaAsigAlta = new DefaultListModel();

        while (itArrayAsig.hasNext()) {
            asig = (Asignatura) itArrayAsig.next();
            modeloListaAsigAlta.addElement(asig.getNombre());
        }
        jLAsignaturasAlta.setModel(modeloListaAsigAlta);
    }

    private void rellenarJlistMod(Asignatura arrayAsigProf[]) {

        modeloListaAsigMod = new DefaultListModel();
        ArrayList<Asignatura> arrayLAsigProf = new ArrayList<>(Arrays.asList(arrayAsigProf));
        Iterator itarrayAsigMod = inici.ArrayLAsignaturas.iterator();

        while (itarrayAsigMod.hasNext()) {
            asig = (Asignatura) itarrayAsigMod.next();
            if (!arrayLAsigProf.contains(asig)) {
                modeloListaAsigMod.addElement(asig.getNombre());
            }
        }
        jLAsignarurasModificacion.setModel(modeloListaAsigMod);
    }

    private void rellenarJlistProfMod(Asignatura arrayAsigProf[]) {
        modeloListaAsigDeProfMod = new DefaultListModel();
        for (Asignatura var : arrayAsigProf) {
            modeloListaAsigDeProfMod.addElement(var.getNombre());
        }
        jLAsignarurasDeProfesorModificacion.setModel(modeloListaAsigDeProfMod);
    }

    private void borrarModeloAsigProf() {
        modeloListaAsigDeProf = new DefaultListModel();
    }

    private void limiarCamposBuscar() {
        modeloListaAsigDeProfMod = new DefaultListModel();
        modeloListaAsigMod = new DefaultListModel();
        jLAsignarurasDeProfesorModificacion.setModel(modeloListaAsigDeProfMod);
        jLAsignarurasModificacion.setModel(modeloListaAsigMod);
        jTFNombreModificacion.setText("");
        jTFTelefonoModificacion.setText("");
        jFTFNifModificacion.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UtilidadesProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UtilidadesProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UtilidadesProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UtilidadesProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UtilidadesProfesor dialog = new UtilidadesProfesor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAddAsignaturaAlta;
    private javax.swing.JButton botonAddAsignaturaModificacio;
    private javax.swing.JButton botonBuscarConsulta;
    private javax.swing.JButton botonBuscarNifModificacion;
    private javax.swing.JButton botonEliminarAsignaturaAlta;
    private javax.swing.JButton botonEliminarAsignaturaProfModificacio;
    private javax.swing.JButton botonEliminarBajaEstudio;
    private javax.swing.JButton botonLimpiarAlta;
    private javax.swing.JButton botonLimpiarBajaEstudio;
    private javax.swing.JButton botonLimpiarmod;
    private javax.swing.JButton botonOKAlta;
    private javax.swing.JButton botonOKModificacio;
    private javax.swing.JFormattedTextField jFTFNifAlta;
    private javax.swing.JFormattedTextField jFTFNifBaja;
    private javax.swing.JFormattedTextField jFTFNifBuscarModificacion;
    private javax.swing.JFormattedTextField jFTFNifConsulta;
    private javax.swing.JFormattedTextField jFTFNifModificacion;
    private javax.swing.JList jLAsignarurasDeProfesorAlta;
    private javax.swing.JList jLAsignarurasDeProfesorModificacion;
    private javax.swing.JList jLAsignarurasModificacion;
    private javax.swing.JList jLAsignaturasAlta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTAConsulta;
    private javax.swing.JTextField jTFNombreAlta;
    private javax.swing.JTextField jTFNombreModificacion;
    private javax.swing.JTextField jTFTelefonoAlta;
    private javax.swing.JTextField jTFTelefonoModificacion;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private void omplirArrayProf(Iterator itArrayAsig, Asignatura[] asignaturas) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
