/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lp2;

import java.awt.Component;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author pere
 */
public class UtilidadesAsignatura extends javax.swing.JDialog {

    Asignatura asignatura;

    public UtilidadesAsignatura(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        jFTFCapacidadModificacion.setEnabled(false);
        JCBTipoClaseModificacion.setEnabled(false);
        botonOKModificacion.setEnabled(false);
        botonCancelarModificacion.setEnabled(false);
        jTFNombreModificacion.setEnabled(false);
        jTFIdentificacionModificacion.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTFNombreAlta = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JCBTipoClaseAlta = new javax.swing.JComboBox();
        botonOkAlta = new javax.swing.JButton();
        botonLimpiarAlta = new javax.swing.JButton();
        jFTFCapacidadAlta = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jFTFIdentificadorAlta = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTAConsulta = new javax.swing.JTextArea();
        botonBuscarConsulta = new javax.swing.JButton();
        jTFNombreConsulta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        botonOKModificacion = new javax.swing.JButton();
        botonCancelarModificacion = new javax.swing.JButton();
        jTFNombreModificacionBuscar = new javax.swing.JFormattedTextField();
        jFTFCapacidadModificacion = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JCBTipoClaseModificacion = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        botonBuscarModificacion = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jTFNombreModificacion = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jTFIdentificacionModificacion = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        botonCancelarBajaEstudio = new javax.swing.JButton();
        botonEliminarBajaEstudio = new javax.swing.JButton();
        jFTFIdentificadorBaja = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Capacidad:");

        jLabel4.setText("Tipo");

        JCBTipoClaseAlta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "A", "B", "C", "D", "E" }));

        botonOkAlta.setText("OK");
        botonOkAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOkAltaActionPerformed(evt);
            }
        });

        botonLimpiarAlta.setText("Limpiar");
        botonLimpiarAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarAltaActionPerformed(evt);
            }
        });

        jFTFCapacidadAlta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel8.setText("Identificador:");

        jFTFIdentificadorAlta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFTFIdentificadorAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFIdentificadorAltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFTFIdentificadorAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonLimpiarAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonOkAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFNombreAlta)
                            .addComponent(JCBTipoClaseAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTFCapacidadAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(212, 212, 212))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFTFIdentificadorAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNombreAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFTFCapacidadAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCBTipoClaseAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonOkAlta)
                    .addComponent(botonLimpiarAlta))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alta", jPanel1);

        jTAConsulta.setColumns(20);
        jTAConsulta.setRows(5);
        jScrollPane3.setViewportView(jTAConsulta);

        botonBuscarConsulta.setText("Buscar");
        botonBuscarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarConsultaActionPerformed(evt);
            }
        });

        jLabel10.setText("Nombre:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNombreConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonBuscarConsulta)
                .addGap(207, 207, 207))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscarConsulta)
                    .addComponent(jTFNombreConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consulta", jPanel4);

        botonOKModificacion.setText("OK");
        botonOKModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOKModificacionActionPerformed(evt);
            }
        });

        botonCancelarModificacion.setText("Cancelar");
        botonCancelarModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarModificacionActionPerformed(evt);
            }
        });

        jTFNombreModificacionBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFNombreModificacionBuscarMouseClicked(evt);
            }
        });

        jFTFCapacidadModificacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel5.setText("Capacidad:");

        jLabel6.setText("Tipo");

        JCBTipoClaseModificacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "A", "B", "C", "D", "E" }));

        jLabel7.setText("Nombre:");

        botonBuscarModificacion.setText("Buscar");
        botonBuscarModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarModificacionActionPerformed(evt);
            }
        });

        jLabel11.setText("Nombre:");

        jTFNombreModificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFNombreModificacionMouseClicked(evt);
            }
        });
        jTFNombreModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreModificacionActionPerformed(evt);
            }
        });

        jLabel12.setText("Identificacion:");

        jTFIdentificacionModificacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jTFIdentificacionModificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFIdentificacionModificacionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel7)
                        .addGap(37, 37, 37)
                        .addComponent(jTFNombreModificacionBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(botonBuscarModificacion))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(botonCancelarModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                    .addComponent(botonOKModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel11))
                                    .addGap(37, 37, 37)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTFIdentificacionModificacion)
                                        .addComponent(JCBTipoClaseModificacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jFTFCapacidadModificacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                        .addComponent(jTFNombreModificacion, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(3, 3, 3)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNombreModificacionBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(botonBuscarModificacion))
                .addGap(35, 35, 35)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFIdentificacionModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNombreModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jFTFCapacidadModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCBTipoClaseModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonOKModificacion)
                    .addComponent(botonCancelarModificacion))
                .addGap(51, 51, 51))
        );

        jTabbedPane1.addTab("Modificacion", jPanel2);

        jLabel9.setText("Identificador:");

        botonCancelarBajaEstudio.setText("Cancelar");
        botonCancelarBajaEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarBajaEstudioActionPerformed(evt);
            }
        });

        botonEliminarBajaEstudio.setText("Eliminar");
        botonEliminarBajaEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarBajaEstudioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(botonCancelarBajaEstudio)
                        .addGap(28, 28, 28)
                        .addComponent(botonEliminarBajaEstudio))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jFTFIdentificadorBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jFTFIdentificadorBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEliminarBajaEstudio)
                    .addComponent(botonCancelarBajaEstudio))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Baja", jPanel3);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Visualización", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonOkAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOkAltaActionPerformed

       
        boolean existeix = false;
        Iterator itArrayAsig = inici.ArrayLAsignaturas.iterator();

        try {

            if ("".equals(jTFNombreAlta.getText()) || "".equals(jFTFCapacidadAlta.getText()) || "-".equals((String) JCBTipoClaseAlta.getSelectedItem())) {

                JOptionPane.showMessageDialog(null,
                        "Hay campos vacios",
                        "Aletra",
                        JOptionPane.WARNING_MESSAGE);
            } else {

                String nombre = jTFNombreAlta.getText();
                String CapacidadString = jFTFCapacidadAlta.getText();
                int Capacidad = Integer.parseInt(CapacidadString);
                String identificadorString = jFTFCapacidadAlta.getText();
                int identificador = Integer.parseInt(identificadorString);
                String Tipo = (String) JCBTipoClaseAlta.getSelectedItem();

                if (!inici.ArrayLAsignaturas.isEmpty()) {

                   

//                    for(int x=0;x<inici.ArrayLAsignaturas.size();x++) {
                       while(itArrayAsig.hasNext()){
                        asignatura = (Asignatura) itArrayAsig.next();
                        if (asignatura.getNombre().equals(jTFNombreAlta.getText())) {
                            existeix = true;
                            JOptionPane.showMessageDialog(null,
                                    "Ya existe la asignatura",
                                    "Aletra",
                                    JOptionPane.WARNING_MESSAGE);
                        } 
                    }
                }
                if (!existeix) {
                    asignatura = new Asignatura(identificador, nombre, Tipo, Capacidad);
                    inici.ArrayLAsignaturas.add(asignatura);
                }

            }
        } catch (Exception ex) {
            Logger.getLogger(UtilidadesAsignatura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonOkAltaActionPerformed

    private void botonLimpiarAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarAltaActionPerformed

        jFTFIdentificadorAlta.setText(null);
        jTFNombreAlta.setText(null);
        jFTFCapacidadAlta.setText(null);
        JCBTipoClaseAlta.setSelectedIndex(0);
    }//GEN-LAST:event_botonLimpiarAltaActionPerformed

    private void botonBuscarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarConsultaActionPerformed
               
       
        Iterator itArrayAsig = inici.ArrayLAsignaturas.iterator();
        System.out.println("Hola hem fet s'iterador");

        if ("".equals(jTFNombreConsulta.getText())) {

            JOptionPane.showMessageDialog(null,
                    "No has escrito ningun identificador",
                    "Aletra",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            if (!inici.ArrayLAsignaturas.isEmpty()) {
                asignatura = (Asignatura) itArrayAsig.next();
                System.out.println(" no esta buit");

               for(int x=0;x<inici.ArrayLAsignaturas.size();x++) {
                  
                    if (asignatura.getNombre().equals(jTFNombreConsulta.getText())) {
                        jTAConsulta.setText(asignatura.toString());
                        System.out.println("trobat");
                    } else {
                        asignatura = (Asignatura) itArrayAsig.next();
                    }

                }
                System.out.println("fora bucle");
            } else {
                jTAConsulta.setText("No hiha cap asignatura donada d'alta");

            }
        }
    }//GEN-LAST:event_botonBuscarConsultaActionPerformed

    private void jTFNombreModificacionBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFNombreModificacionBuscarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreModificacionBuscarMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void botonBuscarModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarModificacionActionPerformed

        Iterator itArrayAsig = inici.ArrayLAsignaturas.iterator();
        System.out.println("Hola hem fet s'iterador");

        if ("".equals(jTFNombreModificacionBuscar.getText())) {

            JOptionPane.showMessageDialog(null,
                    "No has escrito ningun identificador",
                    "Aletra",
                    JOptionPane.WARNING_MESSAGE);
        } else {

            JCBTipoClaseModificacion.setEnabled(true);

            botonOKModificacion.setEnabled(true);
            botonCancelarModificacion.setEnabled(true);

            jTFNombreModificacion.setEnabled(true);
            jTFIdentificacionModificacion.setEnabled(true);
            jFTFCapacidadModificacion.setEnabled(true);

            botonBuscarModificacion.setEnabled(false);

            if (!inici.ArrayLAsignaturas.isEmpty()) {
                asignatura = (Asignatura) itArrayAsig.next();
                System.out.println(" no esta buit");

                for(int x=0;x<inici.ArrayLAsignaturas.size();x++) {
               
                    if (asignatura.getNombre().equals(jTFNombreModificacionBuscar.getText())) {
                        jTFIdentificacionModificacion.setText(String.valueOf(asignatura.getIdentificacion()));
                        jTFNombreModificacion.setText(asignatura.getNombre());
                        jFTFCapacidadModificacion.setText(String.valueOf(asignatura.getCapacidad()));
                        jFTFCapacidadAlta.setText(String.valueOf(asignatura.getCapacidad()));
                        switch (asignatura.getTipo()) {
                            case "A":
                                JCBTipoClaseModificacion.setSelectedIndex(1);
                                break;
                            case "B":
                                JCBTipoClaseModificacion.setSelectedIndex(2);
                                break;
                            case "C":
                                JCBTipoClaseModificacion.setSelectedIndex(3);
                                break;
                            case "D":
                                JCBTipoClaseModificacion.setSelectedIndex(4);
                                break;
                            case "E":
                                JCBTipoClaseModificacion.setSelectedIndex(5);
                                break;
                            default:
                                JCBTipoClaseModificacion.setSelectedIndex(0);
                                break;

                        }
                     
                        System.out.println("trobat");
                    } else {
                        asignatura = (Asignatura) itArrayAsig.next();
                    }

                }
                System.out.println("fora bucle");
            } else {

            }
        }


    }//GEN-LAST:event_botonBuscarModificacionActionPerformed

    private void botonOKModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOKModificacionActionPerformed

        asignatura.setNombre(jTFNombreModificacion.getText());
        asignatura.setIdentificacion(Integer.parseInt(jTFIdentificacionModificacion.getText()));
        asignatura.setCapacidad(Integer.parseInt(jFTFCapacidadModificacion.getText()));
        asignatura.setTipoClase((String) JCBTipoClaseModificacion.getSelectedItem());

        jFTFCapacidadModificacion.setText("");
        jTFIdentificacionModificacion.setText("");
        jTFNombreModificacion.setText("");
        JCBTipoClaseModificacion.setSelectedIndex(0);

        botonOKModificacion.setEnabled(false);
        botonCancelarModificacion.setEnabled(false);
        botonBuscarModificacion.setEnabled(true);

        JCBTipoClaseModificacion.setEnabled(false);

        jFTFCapacidadModificacion.setEnabled(false);
        jTFNombreModificacion.setEnabled(false);
        jTFIdentificacionModificacion.setEnabled(false);


    }//GEN-LAST:event_botonOKModificacionActionPerformed

    private void jTFNombreModificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFNombreModificacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreModificacionMouseClicked

    private void jTFNombreModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreModificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreModificacionActionPerformed

    private void jTFIdentificacionModificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFIdentificacionModificacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFIdentificacionModificacionMouseClicked

    private void botonEliminarBajaEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarBajaEstudioActionPerformed
     
        
        Iterator itArrayAsig = inici.ArrayLAsignaturas.iterator();

        if (!inici.ArrayLAsignaturas.isEmpty()) {
            asignatura = (Asignatura) itArrayAsig.next();

            for(int x=0;x<inici.ArrayLAsignaturas.size();x++) {
           
                if (asignatura.getIdentificacion() == Integer.parseInt(jFTFIdentificadorBaja.getText())) {
                    itArrayAsig.remove();
                    JOptionPane.showMessageDialog(null,
                            "Se ha eliminado correctamente",
                            "Informacion",
                            JOptionPane.INFORMATION_MESSAGE);
                    jFTFIdentificadorBaja.setText("");
                  
                } else {
                    asignatura = (Asignatura) itArrayAsig.next();
                }
            }
        }
    }//GEN-LAST:event_botonEliminarBajaEstudioActionPerformed

    private void botonCancelarModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarModificacionActionPerformed

        jFTFCapacidadModificacion.setText("");
        jTFIdentificacionModificacion.setText("");
        jTFNombreModificacion.setText("");
        JCBTipoClaseModificacion.setSelectedIndex(0);

        botonOKModificacion.setEnabled(false);
        botonCancelarModificacion.setEnabled(false);
        botonBuscarModificacion.setEnabled(true);

        JCBTipoClaseModificacion.setEnabled(false);

        jFTFCapacidadModificacion.setEnabled(false);
        jTFNombreModificacion.setEnabled(false);
        jTFIdentificacionModificacion.setEnabled(false);
    }//GEN-LAST:event_botonCancelarModificacionActionPerformed

    private void botonCancelarBajaEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarBajaEstudioActionPerformed
        jFTFIdentificadorBaja.setText("");
    }//GEN-LAST:event_botonCancelarBajaEstudioActionPerformed

    private void jFTFIdentificadorAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTFIdentificadorAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTFIdentificadorAltaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UtilidadesProfesor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UtilidadesProfesor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UtilidadesProfesor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UtilidadesProfesor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UtilidadesProfesor dialog = new UtilidadesProfesor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JCBTipoClaseAlta;
    private javax.swing.JComboBox JCBTipoClaseModificacion;
    private javax.swing.JButton botonBuscarConsulta;
    private javax.swing.JButton botonBuscarModificacion;
    private javax.swing.JButton botonCancelarBajaEstudio;
    private javax.swing.JButton botonCancelarModificacion;
    private javax.swing.JButton botonEliminarBajaEstudio;
    private javax.swing.JButton botonLimpiarAlta;
    private javax.swing.JButton botonOKModificacion;
    private javax.swing.JButton botonOkAlta;
    private javax.swing.JFormattedTextField jFTFCapacidadAlta;
    private javax.swing.JFormattedTextField jFTFCapacidadModificacion;
    private javax.swing.JFormattedTextField jFTFIdentificadorAlta;
    private javax.swing.JFormattedTextField jFTFIdentificadorBaja;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTAConsulta;
    private javax.swing.JFormattedTextField jTFIdentificacionModificacion;
    private javax.swing.JFormattedTextField jTFNombreAlta;
    private javax.swing.JTextField jTFNombreConsulta;
    private javax.swing.JFormattedTextField jTFNombreModificacion;
    private javax.swing.JFormattedTextField jTFNombreModificacionBuscar;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
