/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lp2;

import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author pere
 */
public class UtilidadesEstudios extends javax.swing.JDialog {

    DefaultListModel modeloListaAsigAlta = new DefaultListModel();
    DefaultListModel modeloListaProfAlta = new DefaultListModel();
    DefaultListModel modeloListaAulaAlta = new DefaultListModel();

    DefaultListModel modeloListaAsigEstudioAlta = new DefaultListModel();
    DefaultListModel modeloListaProfEstudioAlta = new DefaultListModel();
    DefaultListModel modeloListaAulaEstudioAlta = new DefaultListModel();

    Asignatura asig = new Asignatura();
    Profesor prof = new Profesor();
    Aula aula = new Aula();
    Estudios estudio = new Estudios();

    public UtilidadesEstudios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        rellenarJlistAsigAlta();
        rellenarJlistAulaAlta();
        rellenarJlistProfAlta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jFTFIdentificacionAlta = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jTFNombreAlta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCBTipoEstudioAlta = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jFTFFechaComienzoAlta = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jFTFFechaFinalizacionAlta = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jCBTurnoAltaEstudio = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLProfAlta = new javax.swing.JList();
        jLabel10 = new javax.swing.JLabel();
        jCBTipoAlta = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jFTFCapacidadMaxAltaEstudio = new javax.swing.JFormattedTextField();
        botonLimpiarAltaEstudio = new javax.swing.JButton();
        botonOKAltaEstudio = new javax.swing.JButton();
        botonAddProfEstAlta = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jLProfEstudioAlta = new javax.swing.JList();
        botonEliminarProfEstAlta = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        jLAulaAlta = new javax.swing.JList();
        botonAddAulaEstAlta = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        jLAulaEstudioAlta = new javax.swing.JList();
        jScrollPane11 = new javax.swing.JScrollPane();
        jLAsignaturasAlta = new javax.swing.JList();
        jScrollPane12 = new javax.swing.JScrollPane();
        jLAsignaturasEstudioAlta = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        botonEliminarAulaEstAlta = new javax.swing.JButton();
        botonAddAsignaEstAlta = new javax.swing.JButton();
        botonEliminarAsignaturaEstAlta = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jFTFIdentificacionConsulta = new javax.swing.JFormattedTextField();
        botonBuscarConsulta = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTAConsulta = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jFTFCapacidadMaxAltaEstudioMod = new javax.swing.JFormattedTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jCBTipoAltaEstudioMod = new javax.swing.JComboBox();
        jCBTurnoAltaEstudioMod = new javax.swing.JComboBox();
        jFTFFechaFinalizacionMod = new javax.swing.JFormattedTextField();
        jFTFFechaComienzoMod = new javax.swing.JFormattedTextField();
        jCBTipoMod = new javax.swing.JComboBox();
        jTFNombreMod = new javax.swing.JTextField();
        jFTFIdentificacionMod = new javax.swing.JFormattedTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jLAsignaturasMod = new javax.swing.JList();
        jScrollPane14 = new javax.swing.JScrollPane();
        jLAulaMod = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLProfMod = new javax.swing.JList();
        botonAddProfEstMod = new javax.swing.JButton();
        botonEliminarProfEstMod = new javax.swing.JButton();
        botonAddAulaEstMod = new javax.swing.JButton();
        botonEliminarAulaEstMod = new javax.swing.JButton();
        botonAddAsignaEstMod = new javax.swing.JButton();
        botonEliminarAsignaturaEstMod = new javax.swing.JButton();
        jScrollPane15 = new javax.swing.JScrollPane();
        jLAsignaturasEstudioMod = new javax.swing.JList();
        botonLimpiarMod = new javax.swing.JButton();
        botonOKMod = new javax.swing.JButton();
        jScrollPane16 = new javax.swing.JScrollPane();
        jLAulaEstudioMod = new javax.swing.JList();
        jScrollPane17 = new javax.swing.JScrollPane();
        jLProfEstudioMod = new javax.swing.JList();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jFTFIdentificacionBaja = new javax.swing.JFormattedTextField();
        botonEliminarBajaEstudio = new javax.swing.JButton();
        botonLimpiarBajaEstudio = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jFTFIdentificacionAlta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel1.setText("Identificacion:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Estudio:");

        jCBTipoEstudioAlta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Master", "Curso de especialización", "Taller", "Conferencia", "Mesa redonda" }));
        jCBTipoEstudioAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTipoEstudioAltaActionPerformed(evt);
            }
        });

        jLabel4.setText("Fecha comienzo:");

        jFTFFechaComienzoAlta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jFTFFechaComienzoAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFFechaComienzoAltaActionPerformed(evt);
            }
        });

        jLabel5.setText("Fecha finalización:");

        jFTFFechaFinalizacionAlta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jFTFFechaFinalizacionAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFFechaFinalizacionAltaActionPerformed(evt);
            }
        });

        jLabel6.setText("Turno:");

        jCBTurnoAltaEstudio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Mañana", "Tarde", "Mañana y tarde" }));
        jCBTurnoAltaEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTurnoAltaEstudioActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jLProfAlta);

        jLabel10.setText("Tipo");

        jCBTipoAlta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "A", "B", "C", "D", "E", " " }));
        jCBTipoAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTipoAltaActionPerformed(evt);
            }
        });

        jLabel11.setText("<html><body>Capacidad <br> max.est.: </body></html>");

        jFTFCapacidadMaxAltaEstudio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        botonLimpiarAltaEstudio.setText("Limpiar");
        botonLimpiarAltaEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarAltaEstudioActionPerformed(evt);
            }
        });

        botonOKAltaEstudio.setText("Ok");
        botonOKAltaEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOKAltaEstudioActionPerformed(evt);
            }
        });

        botonAddProfEstAlta.setText(">>");
        botonAddProfEstAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAddProfEstAltaActionPerformed(evt);
            }
        });

        jScrollPane8.setViewportView(jLProfEstudioAlta);

        botonEliminarProfEstAlta.setText("<<");
        botonEliminarProfEstAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarProfEstAltaActionPerformed(evt);
            }
        });

        jScrollPane9.setViewportView(jLAulaAlta);

        botonAddAulaEstAlta.setText(">>");
        botonAddAulaEstAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAddAulaEstAltaActionPerformed(evt);
            }
        });

        jScrollPane10.setViewportView(jLAulaEstudioAlta);

        jScrollPane11.setViewportView(jLAsignaturasAlta);

        jScrollPane12.setViewportView(jLAsignaturasEstudioAlta);

        jLabel7.setText("Profesores:");

        jLabel8.setText("Aulas:");

        jLabel9.setText("Asignaturas");

        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Formato: dd/MM/yy");

        botonEliminarAulaEstAlta.setText("<<");
        botonEliminarAulaEstAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarAulaEstAltaActionPerformed(evt);
            }
        });

        botonAddAsignaEstAlta.setText(">>");
        botonAddAsignaEstAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAddAsignaEstAltaActionPerformed(evt);
            }
        });

        botonEliminarAsignaturaEstAlta.setText("<<");
        botonEliminarAsignaturaEstAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarAsignaturaEstAltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFNombreAlta)
                                    .addComponent(jFTFIdentificacionAlta)
                                    .addComponent(jCBTipoEstudioAlta, 0, 128, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jFTFCapacidadMaxAltaEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10))
                                .addGap(84, 84, 84)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCBTipoAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCBTurnoAltaEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(28, 28, 28)
                                .addComponent(jFTFFechaFinalizacionAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFTFFechaComienzoAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botonLimpiarAltaEstudio)
                        .addGap(18, 18, 18)
                        .addComponent(botonOKAltaEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonAddAsignaEstAlta)
                                    .addComponent(botonEliminarAsignaturaEstAlta, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(botonAddProfEstAlta)
                                            .addComponent(botonEliminarProfEstAlta))
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(botonAddAulaEstAlta)
                                            .addComponent(botonEliminarAulaEstAlta))
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(319, 319, 319))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonAddProfEstAlta)
                                .addGap(18, 18, 18)
                                .addComponent(botonEliminarProfEstAlta))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFTFIdentificacionAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTFNombreAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jCBTipoEstudioAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jFTFFechaComienzoAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel5))
                                    .addComponent(jFTFFechaFinalizacionAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(jCBTurnoAltaEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10)
                                            .addComponent(jCBTipoAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(125, 125, 125)
                                        .addComponent(jFTFCapacidadMaxAltaEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(botonAddAulaEstAlta)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonEliminarAulaEstAlta))
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(botonAddAsignaEstAlta)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonEliminarAsignaturaEstAlta)))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(botonLimpiarAltaEstudio)
                                    .addComponent(botonOKAltaEstudio))))))
                .addGap(0, 36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alta", jPanel1);

        jLabel29.setText("Identificacion:");

        jFTFIdentificacionConsulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        botonBuscarConsulta.setText("Buscar");
        botonBuscarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarConsultaActionPerformed(evt);
            }
        });

        jTAConsulta.setColumns(20);
        jTAConsulta.setRows(5);
        jScrollPane7.setViewportView(jTAConsulta);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(48, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addComponent(jFTFIdentificacionConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addGap(24, 24, 24)
                        .addComponent(botonBuscarConsulta)
                        .addGap(420, 420, 420))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTFIdentificacionConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(botonBuscarConsulta))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta", jPanel4);

        jFTFCapacidadMaxAltaEstudioMod.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel26.setText("Identificacion:");

        jLabel27.setText("Nombre:");

        jLabel28.setText("Estudio:");

        jLabel31.setText("Fecha comienzo:");

        jLabel32.setText("Fecha finalización:");

        jLabel33.setText("Turno:");

        jLabel34.setText("Tipo");

        jLabel35.setText("<html><body>Capacidad <br> max.est.: </body></html>");

        jCBTipoAltaEstudioMod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "A", "B", "C", "D", "E", " " }));
        jCBTipoAltaEstudioMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTipoAltaEstudioModActionPerformed(evt);
            }
        });

        jCBTurnoAltaEstudioMod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Mañana", "Tarde", "Mañana y tarde" }));

        jFTFFechaFinalizacionMod.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jFTFFechaFinalizacionMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFFechaFinalizacionModActionPerformed(evt);
            }
        });

        jFTFFechaComienzoMod.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jFTFFechaComienzoMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFFechaComienzoModActionPerformed(evt);
            }
        });

        jCBTipoMod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Master", "Curso de especialización", "Taller", "Conferencia", "Mesa redonda" }));

        jFTFIdentificacionMod.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel36.setText("Profesores:");

        jLabel37.setText("Aulas:");

        jLabel38.setText("Asignaturas");

        jScrollPane13.setViewportView(jLAsignaturasMod);

        jScrollPane14.setViewportView(jLAulaMod);

        jScrollPane2.setViewportView(jLProfMod);

        botonAddProfEstMod.setText(">>");

        botonEliminarProfEstMod.setText("<<");
        botonEliminarProfEstMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarProfEstModActionPerformed(evt);
            }
        });

        botonAddAulaEstMod.setText(">>");

        botonEliminarAulaEstMod.setText("<<");

        botonAddAsignaEstMod.setText(">>");

        botonEliminarAsignaturaEstMod.setText("<<");

        jScrollPane15.setViewportView(jLAsignaturasEstudioMod);

        botonLimpiarMod.setText("Limpiar");
        botonLimpiarMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarModActionPerformed(evt);
            }
        });

        botonOKMod.setText("Ok");
        botonOKMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOKModActionPerformed(evt);
            }
        });

        jScrollPane16.setViewportView(jLAulaEstudioMod);

        jScrollPane17.setViewportView(jLProfEstudioMod);

        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Formato: dd/MM/yy");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBTipoAltaEstudioMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBTurnoAltaEstudioMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTFCapacidadMaxAltaEstudioMod, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(jFTFFechaComienzoMod)
                            .addComponent(jFTFFechaFinalizacionMod))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel38)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(botonEliminarAsignaturaEstMod)
                                .addComponent(botonAddAsignaEstMod))
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel36)
                                .addComponent(jLabel37))
                            .addGap(43, 43, 43)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(botonAddProfEstMod)
                                        .addComponent(botonEliminarProfEstMod))
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(botonAddAulaEstMod)
                                        .addComponent(botonEliminarAulaEstMod))
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botonLimpiarMod)
                        .addGap(18, 18, 18)
                        .addComponent(botonOKMod, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel26)
                        .addComponent(jLabel27)
                        .addComponent(jLabel28))
                    .addGap(48, 48, 48)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTFNombreMod)
                        .addComponent(jFTFIdentificacionMod)
                        .addComponent(jCBTipoMod, 0, 128, Short.MAX_VALUE))
                    .addContainerGap(522, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(21, 221, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(botonAddProfEstMod)
                                .addGap(18, 18, 18)
                                .addComponent(botonEliminarProfEstMod))
                            .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(botonAddAulaEstMod)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonEliminarAulaEstMod)
                                        .addGap(43, 43, 43))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel31)
                                            .addComponent(jFTFFechaComienzoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel32)
                                            .addComponent(jFTFFechaFinalizacionMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel37))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(botonAddAsignaEstMod)
                                .addGap(18, 18, 18)
                                .addComponent(botonEliminarAsignaturaEstMod)))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonLimpiarMod)
                            .addComponent(botonOKMod)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(jCBTurnoAltaEstudioMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(jCBTipoAltaEstudioMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTFCapacidadMaxAltaEstudioMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFTFIdentificacionMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFNombreMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(jCBTipoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(339, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Modificacion", jPanel2);

        jLabel30.setText("Identificacion:");

        jFTFIdentificacionBaja.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        botonEliminarBajaEstudio.setText("Eliminar");

        botonLimpiarBajaEstudio.setText("Limpiar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(36, 36, 36)
                        .addComponent(jFTFIdentificacionBaja))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(botonLimpiarBajaEstudio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminarBajaEstudio)))
                .addGap(329, 329, 329))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTFIdentificacionBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(86, 86, 86)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEliminarBajaEstudio)
                    .addComponent(botonLimpiarBajaEstudio))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Baja", jPanel3);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Visualización", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBTipoAltaEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoAltaEstudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTipoAltaEstudioActionPerformed

    private void botonEliminarProfEstAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarProfEstAltaActionPerformed
        if (jLProfEstudioAlta.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(null,
                    "Selecciona un profesor",
                    "Informacion",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            modeloListaProfAlta.addElement(jLProfEstudioAlta.getSelectedValue());
            modeloListaProfEstudioAlta.removeElementAt(jLProfEstudioAlta.getSelectedIndex());
            jLProfAlta.setModel(modeloListaProfAlta);
        }
    }//GEN-LAST:event_botonEliminarProfEstAltaActionPerformed

    private void jCBTipoAltaEstudioModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoAltaEstudioModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTipoAltaEstudioModActionPerformed

    private void botonEliminarProfEstModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarProfEstModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarProfEstModActionPerformed

    private void botonOKAltaEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOKAltaEstudioActionPerformed
        if ("".equals(jTFNombreAlta.getText()) || "".equals(jFTFIdentificacionAlta.getText()) || "".equals(jFTFCapacidadMaxAltaEstudio.getText())
                || "".equals(jFTFFechaComienzoAlta.getText()) || "".equals(jFTFFechaFinalizacionAlta.getText())) {

            JOptionPane.showMessageDialog(null,
                    "Hay campos vacios",
                    "Aletra",
                    JOptionPane.WARNING_MESSAGE);
        } else {

            Iterator<Estudios> itArrayEstu = inici.ArrayEstudios.iterator();
            //collim tots els valors de jList
            Object[] nomAsignaturas = modeloListaAsigEstudioAlta.toArray();
            String[] asignaturas = new String[nomAsignaturas.length];
            Object[] nomProfesores = modeloListaProfEstudioAlta.toArray();
            String[] profesores = new String[nomProfesores.length];
            Object[] nomAulas = modeloListaAulaEstudioAlta.toArray();
            int[] aulas = new int[nomAulas.length];
            boolean existeix = false; //cercam l'aula si esta creada
            while (itArrayEstu.hasNext() && !existeix) {
                estudio = (Estudios) itArrayEstu.next();
                if (estudio.getNombre().equals(jTFNombreAlta.getText())) {

                    JOptionPane.showMessageDialog(null,
                            "Ya se ha dado de alta este profesor",
                            "Aletra",
                            JOptionPane.WARNING_MESSAGE);
                }
            }
            if (!existeix) {
                ////////////////////////////////////////////////////////////////////////////////////
                //rellenam arrays de  asignatures, professors i aules
                System.out.println("asig");
                for (int i = 0; i < nomAsignaturas.length; i++) {
                    Iterator itArrayAsig = inici.ArrayLAsignaturas.iterator();
                    while (itArrayAsig.hasNext()) {
                        asig = (Asignatura) itArrayAsig.next();
                        if (asig.getNombre().equals(nomAsignaturas[i])) {
                            asignaturas[i] = asig.getNombre();
                            System.out.println("dedins bulcle asig");
                            System.out.println(asig.toString());
                        }
                        System.out.println(i);
                    }
                }
                System.out.println("pprof");
                for (int i = 0; i < nomProfesores.length; i++) {
                    Iterator itArrayProf = inici.ArrayProfesor.iterator();
                    while (itArrayProf.hasNext()) {
                        prof = (Profesor) itArrayProf.next();
                        if (prof.getNombre().equals(nomAsignaturas[i])) {
                            profesores[i] = prof.getNombre();
                            System.out.println("dedins bulcle prof");
                            System.out.println(prof.toString());
                        }
                        System.out.println(i);
                    }
                }
                System.out.println("aula");
                for (int i = 0; i < nomAulas.length; i++) {
                    Iterator itArrayAulas = inici.ArrayAula.iterator();
                    while (itArrayAulas.hasNext()) {
                        aula = (Aula) itArrayAulas.next();
                        if (String.valueOf(aula.getIdentificacion()).equals(nomAulas[i])) {
                            aulas[i] = aula.getIdentificacion();
                            System.out.println("dedins bulcle aules");
                            System.out.println(aula.toString());
                        }
                        System.out.println(i);
                    }
                }

//donar d'alta estudi
                try {
                    estudio = new Estudios(Integer.parseInt(jFTFIdentificacionAlta.getText()), jTFNombreAlta.getText(),
                            jCBTipoEstudioAlta.getSelectedItem().toString(), jFTFFechaComienzoAlta.getText(),
                            jFTFFechaFinalizacionAlta.getText(), jCBTurnoAltaEstudio.getSelectedItem().toString(),
                            asignaturas, aulas, profesores, jCBTipoAlta.getSelectedItem().toString(),
                            Integer.parseInt(jFTFCapacidadMaxAltaEstudio.getText()));
                    inici.ArrayEstudios.add(estudio);
                    System.out.println(estudio);

                } catch (Exception e) {
                    System.out.println(e);
                }

                ///////////////////////////////////////////////////////////////////////////////////
            }

        }
    }//GEN-LAST:event_botonOKAltaEstudioActionPerformed

    private void botonOKAltaEstudio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOKAltaEstudio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonOKAltaEstudio1ActionPerformed

    private void jCBTipoEstudioAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoEstudioAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTipoEstudioAltaActionPerformed

    private void jFTFFechaComienzoModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTFFechaComienzoModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTFFechaComienzoModActionPerformed

    private void jFTFFechaComienzoAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTFFechaComienzoAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTFFechaComienzoAltaActionPerformed

    private void jCBTurnoAltaEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTurnoAltaEstudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTurnoAltaEstudioActionPerformed

    private void botonLimpiarAltaEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarAltaEstudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLimpiarAltaEstudioActionPerformed

    private void botonAddProfEstAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAddProfEstAltaActionPerformed

        if (jLProfAlta.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(null,
                    "Selecciona un profesor",
                    "Informacion",
                    JOptionPane.WARNING_MESSAGE);

        } else {
            modeloListaProfEstudioAlta.addElement(jLProfAlta.getSelectedValue());
            modeloListaProfAlta.removeElementAt(jLProfAlta.getSelectedIndex());
            jLProfEstudioAlta.setModel(modeloListaProfEstudioAlta);

        }


    }//GEN-LAST:event_botonAddProfEstAltaActionPerformed

    private void botonAddAulaEstAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAddAulaEstAltaActionPerformed
        if (jLAulaAlta.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(null,
                    "Selecciona una aula",
                    "Informacion",
                    JOptionPane.WARNING_MESSAGE);

        } else {
            modeloListaAulaEstudioAlta.addElement(jLAulaAlta.getSelectedValue());
            modeloListaAulaAlta.removeElementAt(jLAulaAlta.getSelectedIndex());
            jLAulaEstudioAlta.setModel(modeloListaAulaEstudioAlta);
        }
    }//GEN-LAST:event_botonAddAulaEstAltaActionPerformed


    private void botonBuscarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarConsultaActionPerformed
        Iterator itArrayEstudios = inici.ArrayEstudios.iterator();
        boolean trobat = false;
        if ("".equals(jFTFIdentificacionConsulta.getText())) {

            JOptionPane.showMessageDialog(null,
                    "No has escrito ningun identificador",
                    "Aletra",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            if (!inici.ArrayEstudios.isEmpty()) {

                while (itArrayEstudios.hasNext() && trobat) {
                    estudio = (Estudios) itArrayEstudios.next();
                    System.out.println(estudio.getIdentificacion() + " == " + Integer.parseInt(jFTFIdentificacionConsulta.getText()));
                    if (estudio.getIdentificacion() == Integer.parseInt(jFTFIdentificacionConsulta.getText())) {
                        trobat = true;
                        jTAConsulta.setText(estudio.toString());

                    }
                }
                if (!trobat) {
                    jTAConsulta.setText("No hay ningun estudio dado de alta con este Nif");
                }

            } else {
                jTAConsulta.setText("No hay ningun estudio dado de alta");

            }
        }
    }//GEN-LAST:event_botonBuscarConsultaActionPerformed

    private void botonEliminarAulaEstAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarAulaEstAltaActionPerformed

        if (jLAulaEstudioAlta.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(null,
                    "Selecciona Aula",
                    "Informacion",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            modeloListaAulaAlta.addElement(jLAulaEstudioAlta.getSelectedValue());
            modeloListaAulaEstudioAlta.removeElementAt(jLAulaEstudioAlta.getSelectedIndex());
            jLAsignaturasAlta.setModel(modeloListaAulaAlta);

        }

    }//GEN-LAST:event_botonEliminarAulaEstAltaActionPerformed

    private void botonAddAsignaEstAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAddAsignaEstAltaActionPerformed

        if (jLAsignaturasAlta.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(null,
                    "Selecciona una asignatura",
                    "Informacion",
                    JOptionPane.WARNING_MESSAGE);

        } else {
            modeloListaAsigEstudioAlta.addElement(jLAsignaturasAlta.getSelectedValue());
            modeloListaAsigAlta.removeElementAt(jLAsignaturasAlta.getSelectedIndex());
            jLAsignaturasEstudioAlta.setModel(modeloListaAsigEstudioAlta);

        }
    }//GEN-LAST:event_botonAddAsignaEstAltaActionPerformed

    private void botonEliminarAsignaturaEstAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarAsignaturaEstAltaActionPerformed

        if (jLAsignaturasEstudioAlta.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(null,
                    "Selecciona asignatura",
                    "Informacion",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            modeloListaAsigAlta.addElement(jLAsignaturasEstudioAlta.getSelectedValue());
            modeloListaAsigEstudioAlta.removeElementAt(jLAsignaturasEstudioAlta.getSelectedIndex());
            jLAsignaturasEstudioAlta.setModel(modeloListaAsigAlta);
            jLAsignaturasEstudioAlta.setModel(modeloListaAsigEstudioAlta);
        }
    }//GEN-LAST:event_botonEliminarAsignaturaEstAltaActionPerformed

    private void jCBTipoAltaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jFTFFechaFinalizacionModActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void jFTFFechaFinalizacionAltaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void botonLimpiarModActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("funciona es parxe");
    }

    private void botonOKModActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void rellenarJlistAsigAlta() {
        Iterator itArrayAsig = inici.ArrayLAsignaturas.iterator();
        modeloListaAsigAlta = new DefaultListModel();

        while (itArrayAsig.hasNext()) {
            asig = (Asignatura) itArrayAsig.next();
            modeloListaAsigAlta.addElement(asig.getNombre());
        }
        jLAsignaturasAlta.setModel(modeloListaAsigAlta);

    }

    private void rellenarJlistProfAlta() {
        Iterator itArrayProf = inici.ArrayProfesor.iterator();
        modeloListaProfAlta = new DefaultListModel();

        while (itArrayProf.hasNext()) {
            prof = (Profesor) itArrayProf.next();
            modeloListaProfAlta.addElement(prof.getNombre());
        }
        jLProfAlta.setModel(modeloListaProfAlta);

    }

    private void rellenarJlistAulaAlta() {
        Iterator itArrayProf = inici.ArrayAula.iterator();
        modeloListaAulaAlta = new DefaultListModel();

        while (itArrayProf.hasNext()) {
            aula = (Aula) itArrayProf.next();
            modeloListaAulaAlta.addElement(aula.getIdentificacion());
        }
        jLAulaAlta.setModel(modeloListaAulaAlta);

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UtilidadesEstudios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UtilidadesEstudios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UtilidadesEstudios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UtilidadesEstudios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UtilidadesEstudios dialog = new UtilidadesEstudios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAddAsignaEstAlta;
    private javax.swing.JButton botonAddAsignaEstMod;
    private javax.swing.JButton botonAddAulaEstAlta;
    private javax.swing.JButton botonAddAulaEstMod;
    private javax.swing.JButton botonAddProfEstAlta;
    private javax.swing.JButton botonAddProfEstMod;
    private javax.swing.JButton botonBuscarConsulta;
    private javax.swing.JButton botonEliminarAsignaturaEstAlta;
    private javax.swing.JButton botonEliminarAsignaturaEstMod;
    private javax.swing.JButton botonEliminarAulaEstAlta;
    private javax.swing.JButton botonEliminarAulaEstMod;
    private javax.swing.JButton botonEliminarBajaEstudio;
    private javax.swing.JButton botonEliminarProfEstAlta;
    private javax.swing.JButton botonEliminarProfEstMod;
    private javax.swing.JButton botonLimpiarAltaEstudio;
    private javax.swing.JButton botonLimpiarBajaEstudio;
    private javax.swing.JButton botonLimpiarMod;
    private javax.swing.JButton botonOKAltaEstudio;
    private javax.swing.JButton botonOKMod;
    private javax.swing.JComboBox jCBTipoAlta;
    private javax.swing.JComboBox jCBTipoAltaEstudioMod;
    private javax.swing.JComboBox jCBTipoEstudioAlta;
    private javax.swing.JComboBox jCBTipoMod;
    private javax.swing.JComboBox jCBTurnoAltaEstudio;
    private javax.swing.JComboBox jCBTurnoAltaEstudioMod;
    private javax.swing.JFormattedTextField jFTFCapacidadMaxAltaEstudio;
    private javax.swing.JFormattedTextField jFTFCapacidadMaxAltaEstudioMod;
    private javax.swing.JFormattedTextField jFTFFechaComienzoAlta;
    private javax.swing.JFormattedTextField jFTFFechaComienzoMod;
    private javax.swing.JFormattedTextField jFTFFechaFinalizacionAlta;
    private javax.swing.JFormattedTextField jFTFFechaFinalizacionMod;
    private javax.swing.JFormattedTextField jFTFIdentificacionAlta;
    private javax.swing.JFormattedTextField jFTFIdentificacionBaja;
    private javax.swing.JFormattedTextField jFTFIdentificacionConsulta;
    private javax.swing.JFormattedTextField jFTFIdentificacionMod;
    private javax.swing.JList jLAsignaturasAlta;
    private javax.swing.JList jLAsignaturasEstudioAlta;
    private javax.swing.JList jLAsignaturasEstudioMod;
    private javax.swing.JList jLAsignaturasMod;
    private javax.swing.JList jLAulaAlta;
    private javax.swing.JList jLAulaEstudioAlta;
    private javax.swing.JList jLAulaEstudioMod;
    private javax.swing.JList jLAulaMod;
    private javax.swing.JList jLProfAlta;
    private javax.swing.JList jLProfEstudioAlta;
    private javax.swing.JList jLProfEstudioMod;
    private javax.swing.JList jLProfMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTAConsulta;
    private javax.swing.JTextField jTFNombreAlta;
    private javax.swing.JTextField jTFNombreMod;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
